### ISSUE TITLE
Cannot load OS (2nd)

### ISSUE THREAD

**Issue by leomil72** [MightyPirates/OpenComputers#2650]
This ticket follows #2638 where I used Shiginima (I didn't know that it was a cracked version, a son of mine told me to use it).
Today I bought a genuine copy from Mojang, and started again Minecraft to try OpenComputers.
I used my previous installation with Industrial Craft2, Actually Additions and OpenComputers on 1.12.1 then I launched the game and created a new world. Then I got in Creative and assembled a computer and tried to power it up but got the same error of the last time, that the computer cannot load OS because it didn't find /init.lua
You can see here a screenshot:
![2017-11-29_17 58 20](https://user-images.githubusercontent.com/1081865/33388238-b6d732c4-d52f-11e7-9103-08d71c0ef868.png)

Can anyone help me, please?

**Comment by payonel** [comment]
welcome back :)
Well interesting -- I'll follow your steps and retest.

What would help even more is if you could send me a zip of your minecraft folder.
What launcher are you using to play? 

If you are using multimc use their export feature and send me the zip. You don't have to be using multimc to share this.
If you are not using multimc, If you could zip the whole minecraft folder so that i get the same configs, mods, and world save so i can retest

If you decide you can send me this zip file, please talk to me on irc here: https://webchat.esper.net/?channels=oc

**Comment by leomil72** [comment]
File has been uploaded - thank you for your interest.

**Comment by payonel** [comment]
@leomil72 can you explain how you downloaded opencomputers? I know you are using modloader, but, if you could explain the steps you used to download our mod? what site did you use? or what tool?

The reason I ask is because the OpenComputers jar I found in your zip was a bit odd
1. It reported itself to be version 1.7.0.20, which matches our latest release version. But, the filename was modified and when I inspected the class files - they did not match the class files in our official version.
2. When i used the same jar from your zip I also fail use components in the game world. But if I replace your copy of our mod with a clean download of the our mod, then your example save file and the repro you gave me is fixed.

You can download our mod from: https://minecraft.curseforge.com/projects/opencomputers/files
Use the 1.12.2 game version jar in that list, or this direct link: https://minecraft.curseforge.com/projects/opencomputers/files/2490748/download

**Comment by payonel** [comment]
@leomil72 my guess is that you downloaded a version of our mod that was modified by a third party. Please only use our mod downloads from curseforge (the link I gave, but here again: https://minecraft.curseforge.com/projects/opencomputers/files ) or feel free to use our latest builds from our build server ( http://ci.cil.li/ ). You should delete the old jars you previously downloaded (all of them) and download release versions of those mods from curseforge (for example, you have actually additions, but it is also a strangely-modified version of the real one)

**Comment by leomil72** [comment]
Sorry but I tried to download the filed from where you said but I still continue to get the same error message. I don't understand why..

**Comment by payonel** [comment]
I doubt you are loading the mod correctly

I don't use the vanilla launcher to manage modpacks. I sure it is possible, but, I strongly recommend MultiMC (mmc): https://multimc.org/
mmc is only a launcher for minecraft, you still have to use your real mojang account.
In mmc you create a new instance for each modpack or vanilla version of the game you want to have for use. Then you add forge to an instance, and can add mods to its mod folder. It is worth learning to use.

If you have more questions, please reach out to me in irc again ( https://webchat.esper.net/?channels=oc )

**Comment by leomil72** [comment]
I finally was able to launch OpenOS from the floppy disk!! I'm very happy, thank you!! :-)
So, I for sure can say that the mod isn't compatible with no launcher but MultiMC, so I suggest you that you should inform the users that "it is recommended to use MultiMC" to avoid other launchers' users like me to go grazy trying to use the mod :-)
BTW, thanks again for your support :-)

**Comment by payonel** [comment]
@leomil72 what launcher were you using? can you provide me a link? We do not require multimc, multimc is good at helping people set up mods correctly. We require Forge to be installed in the client, and then our mod placed in the mods folder for the minecraft instance they are going to run. Much of that process is simplified with multimc, but definitely can be done without it.

**Comment by leomil72** [comment]
I used MC ModInstaller 5.0.8 to install mods then I used first Shiginima Launcher 3.10 and, lately, I used the original launcher of the game.
